GET http://localhost:8080/api/cinema
Accept: application/json

###
POST http://localhost:8080/api/cinema
Content-Type: application/json

{
  "title": "",
  "date" : [2021,6,30,12,30],
  "maxReservation": 120
}

###
POST http://localhost:8080/api/cinema
Content-Type: application/json

{
  "title": "Titanic",
  "date" : [2021,6,30,12,30],
  "maxReservation": 120
}

###
PUT http://localhost:8080/api/cinema/1/reserve
Content-Type: application/json

{
  "reservationNumber": 121
}

###
PUT http://localhost:8080/api/cinema/1/reserve
Content-Type: application/json

{
  "reservationNumber": 2
}